name: PlayerlyAPI
description: playerly api for stats
version: 0.1.0 
api: 4.0.0 # for 5.0.0, check 5.0.0 branch, 3.0.0 (if using betteraltay or ?) will be implemented in the future mabye! 
author: [Toxic, UnknownNull]
main: Toxic\Stats

commands:
  stats:
    description: "Check your stats or another players"
    aliases: [profile, user]
    permission: toxic.stats.command
 
permissions:
  toxic.stats.command:
    default: true
  toxic.unmute.command:
    default: op
  toxic.mute.command:
    default: op
  toxic.ban.command:
    default: op
  toxic.unban.command:
    default: op
  toxic.opcoins.command:
    default: op