name: PlayerlyAPI
description: playerly api for stats
version: 1.0.0 # SemVer
api: 4.0.0 # 5.0.0 soon!
author: [Toxic, UnknownNull]
main: Toxic\Stats

commands:
  stats:
    description: "Check your stats or another players"
    aliases: [profile, user]
    permission: toxic.stats.command
 
permissions:
  toxic.stats.command:
    default: true
  toxic.unmute.command:
    default: op
  toxic.mute.command:
    default: op